import {
  requireAuth,
  supabaseRequest,
  json,
  notifyChat,
  fmtMoney,
  fmtDateHuman,
} from "./_utils.js";

function escapeHtml(str) {
  return String(str).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
}

// POST /api/transfers
// Moves money between two accounts. A transfer is NOT income or expense, so it never
// touches budgets or the income/expense reports. The only exception is the fee: when the
// source account is in IDR the fee is also booked as a normal Taxes & Fees expense, so
// every existing report and budget alert includes it.
export async function onRequestPost(context) {
  const { request, env } = context;

  const auth = await requireAuth(request, env);
  if (!auth) return json({ error: "unauthorized" }, 401);

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "invalid JSON body" }, 400);
  }

  const { transfer_date, transfer_time, from_account_id, to_account_id, amount_out, amount_in, fee_amount, description } =
    body || {};

  if (!transfer_date || !/^\d{4}-\d{2}-\d{2}$/.test(transfer_date)) {
    return json({ error: "transfer_date must be YYYY-MM-DD" }, 400);
  }
  const time = /^\d{2}:\d{2}(:\d{2})?$/.test(transfer_time || "") ? transfer_time : "12:00";

  const fromId = Number(from_account_id);
  const toId = Number(to_account_id);
  if (!Number.isInteger(fromId) || !Number.isInteger(toId)) {
    return json({ error: "from_account_id and to_account_id must be integers" }, 400);
  }
  if (fromId === toId) return json({ error: "from and to account must be different" }, 400);

  const out = Number(amount_out);
  if (!Number.isFinite(out) || out <= 0) return json({ error: "amount_out must be a positive number" }, 400);

  const fee = fee_amount === undefined || fee_amount === null || fee_amount === "" ? 0 : Number(fee_amount);
  if (!Number.isFinite(fee) || fee < 0) return json({ error: "fee_amount must be zero or a positive number" }, 400);

  const desc = typeof description === "string" && description.trim() ? description.trim().slice(0, 500) : null;

  // --- Accounts: both must exist; currency decides whether amount_in is needed ---
  const accRes = await supabaseRequest(env, `payment_accounts?id=in.(${fromId},${toId})&select=id,name,currency`);
  if (!accRes.ok) return json({ error: "validation lookup failed" }, 502);
  const accRows = await accRes.json();
  const from = accRows.find((a) => a.id === fromId);
  const to = accRows.find((a) => a.id === toId);
  if (!from || !to) return json({ error: "unknown payment account" }, 400);

  const sameCurrency = (from.currency || "IDR") === (to.currency || "IDR");
  const inAmt = sameCurrency ? out : Number(amount_in);
  if (!Number.isFinite(inAmt) || inAmt <= 0) {
    return json({ error: `amount_in is required because ${from.name} and ${to.name} use different currencies` }, 400);
  }

  // --- Insert the transfer (txn_no is generated by a database trigger) ---
  const insertRes = await supabaseRequest(env, "transfers", {
    method: "POST",
    headers: { Prefer: "return=representation" },
    body: JSON.stringify({
      transfer_date,
      transfer_time: time,
      from_account_id: fromId,
      to_account_id: toId,
      amount_out: out,
      amount_in: inAmt,
      fee_amount: fee,
      description: desc,
      telegram_user_id: auth.user.id,
    }),
  });
  if (!insertRes.ok) {
    return json({ error: "insert failed", detail: await insertRes.text() }, 502);
  }
  const [row] = await insertRes.json();

  // --- Book the fee as an expense (IDR source accounts only; the ledger is IDR-only) ---
  let feeNote = "-";
  if (fee > 0) {
    if ((from.currency || "IDR") !== "IDR") {
      feeNote = `${fmtMoney(fee, from.currency)} (kept on the transfer only, the expense ledger is IDR)`;
    } else {
      const ok = await bookFeeExpense(env, { row, fee, from, transfer_date, time, userId: auth.user.id });
      if (!ok) {
        // Roll back so a transfer never exists with a fee that is missing from the reports.
        await supabaseRequest(env, `transfers?id=eq.${row.id}`, { method: "DELETE" });
        return json({ error: "could not book the fee as an expense; transfer was not saved" }, 502);
      }
      feeNote = `${fmtMoney(fee, "IDR")} (booked as a Taxes & Fees expense)`;
    }
  }

  // --- Notify the shared group (best-effort) ---
  const submittedBy = auth.user.first_name || auth.user.username || "Someone";
  const moved = sameCurrency
    ? `${fmtMoney(out, from.currency)} from ${escapeHtml(from.name)} to ${escapeHtml(to.name)}`
    : `${fmtMoney(out, from.currency)} out of ${escapeHtml(from.name)}, ${fmtMoney(inAmt, to.currency)} into ${escapeHtml(to.name)}`;
  const lines = [
    `<b>TRANSFER LOGGED</b> · #${row.txn_no || row.id}`,
    `- at ${fmtDateHuman(transfer_date)} ${time} by ${escapeHtml(submittedBy)}`,
    `- ${moved}`,
    `- Fee: ${feeNote}`,
    `- Note: ${desc ? escapeHtml(desc) : "-"}`,
  ];
  await notifyChat(env, lines.join("\n"));

  return json({ ok: true, transfer: row });
}

async function bookFeeExpense(env, { row, fee, from, transfer_date, time, userId }) {
  try {
    // Look the ids up by name so nothing is hard-coded.
    const subRes = await supabaseRequest(
      env,
      `expense_subcategories?name=eq.${encodeURIComponent("Taxes & Fees")}&select=id,category_id`
    );
    if (!subRes.ok) return false;
    const [sub] = await subRes.json();
    if (!sub) return false;

    const [y, m] = transfer_date.split("-").map(Number);
    const noRes = await supabaseRequest(env, "rpc/next_txn_no", {
      method: "POST",
      body: JSON.stringify({ p_year: y, p_month: m }),
    });
    const txnNo = noRes.ok ? await noRes.json() : null;

    const ledgerRes = await supabaseRequest(env, "expense_ledger", {
      method: "POST",
      headers: { Prefer: "return=representation" },
      body: JSON.stringify({
        expense_date: transfer_date,
        expense_time: time,
        category_id: sub.category_id,
        subcategory_id: sub.id,
        account_id: from.id,
        used_by_ids: [],
        amount: fee,
        description: `Transfer fee ${row.txn_no || row.id}`,
        tags: ["transfer-fee"],
        txn_no: txnNo,
        telegram_user_id: userId,
        source: "telegram",
      }),
    });
    if (!ledgerRes.ok) return false;
    const [ledger] = await ledgerRes.json();

    const linkRes = await supabaseRequest(env, `transfers?id=eq.${row.id}`, {
      method: "PATCH",
      body: JSON.stringify({ fee_ledger_id: ledger.id }),
    });
    if (!linkRes.ok) {
      await supabaseRequest(env, `expense_ledger?id=eq.${ledger.id}`, { method: "DELETE" });
      return false;
    }
    return true;
  } catch {
    return false;
  }
}
